### ISSUE TITLE
import viewshed leads to OSRImportFromProj4 error

### ISSUE THREAD

**Issue by WorksWellWithOthers** [jonnyhuck/Viewshed#17]
`    import _viewshed
ImportError: /home/dummy/Viewshed/_viewshed.cpython-39-x86_64-linux-gnu.so: undefined symbol: OSRImportFromProj4`

**Comment by jonnyhuck** [comment]
Thanks for reporting this- Could you give the steps to reproduce this error please?

**Comment by WorksWellWithOthers** [comment]
I think this has to do with my GDAL and Proj versions being mismatched. 
[Similar Problem?](https://gis.stackexchange.com/questions/157059/repairing-broken-gdal-and-proj-4-on-ubuntu)
