### ISSUE TITLE
Can Viewshed load .dt0 files?

### ISSUE THREAD

**Issue by WorksWellWithOthers** [jonnyhuck/Viewshed#19]
Would I be able to load dt0 files or would I have to generate .tif from a collection of .dt0 files?

**Comment by jonnyhuck** [comment]
I am not familiar with that format, but It can load anything that GDAL can load- the list is [here](https://gdal.org/drivers/raster/index.html) - does that answer it?

**Comment by WorksWellWithOthers** [comment]
Thank you for the list.
It looks like DTED is supported.
