### ISSUE TITLE
build command fails

### ISSUE THREAD

**Issue by kolesar-andras** [jonnyhuck/Viewshed#3]
I have tried to build executable using the command from [README](../blob/38080c77af684cc59af95c53991fed8482b57af0/README.md):

    $ gcc viewshed.cpp -framework GDAL -o viewshed -O3
    gcc: error: GDAL: No such file or directory
    gcc: error: unrecognized command line option '-framework'

I use Ubuntu 16.04.2 LTS with `gdal` istalled.

**Comment by kolesar-andras** [comment]
Command for successful build:

    gcc viewshed.cpp -lgdal -lm -o viewshed -O3

Requirements do not mention necessary package `libgdal-dev`.

**Comment by jonnyhuck** [comment]
Thanks for this @kolesar-andras - we should have been clearer in the README that those commands are for Mac. Thanks for contributing the working Linux command, that is really helpful!

Please do push any improvements that you make - we've been meaning to get back on to this project.

Thanks again!
