### ISSUE TITLE
which algorithm is this based on?

### ISSUE THREAD

**Issue by songololo** [jonnyhuck/Viewshed#5]
@jonnyhuck Is this package based on one of the fairly typical viewshed algorithms? e.g. R2, R3, Xdraw etc?

If not, is there any sense for where this shakes out in terms of performance vs. accuracy?

Thanks

**Comment by jonnyhuck** [comment]
Hi @shongololo, thanks for getting in touch!

It is roughly R2, and it uses Bresenhams line algorithm to cast each ray. We wrote it with the intention of it being quite a 'quick and dirty' approach, so it is probably about as fast as it gets without using graphics cards etc., but the Bresenhams line stuff isn't always as good as you could get with a trig offset from an accuracy perspective. I've been meaning to do some work on this for a while - so please do push any improvements back up!

Also - just be aware that the projection is currently hard-coded to British National Grid, that definitely needs changing!
