### ISSUE TITLE
I need one sample for used this project in c++, pls.

### ISSUE THREAD

**Issue by morteza2m** [jonnyhuck/Viewshed#6]
hi.
I need one sample for used this project in c++, pls.

**Comment by morteza2m** [comment]
Error in use this project:
`./viewshed -r 2000 -x 20 -y 30 -i dem.tif -f out.tif`

Error in terminal:
```
ERROR 5: dem.tif, band 1: Access window out of range in RasterIO().  Requested
(-37,-39) of size 80x80 on raster of 7212x7212
```

**Comment by jonnyhuck** [comment]
What projection are you using for dem.tif? The code is currently hard-coded using the British National Grid (_I've not got round to adding this as an option - it is on the TODO list!_). If you are using a different projection, simply change the proj4 string on line 762 for the one that you are using and it should work fine!

If you're not sure where to get a proj4 string from, simply search for your projection on [spatialreference.org](http://spatialreference.org) and you can click the proj4 link to get it. For example, if you were using the Irish National Grid then searching the site would give you [this page](http://spatialreference.org/ref/epsg/29901/), and following the proj4 link would give you [this](http://spatialreference.org/ref/epsg/29901/proj4/), which you can copy and paste over the second argument in line 762. _(Apologies if you already knew all that!)_

Any use?

**Comment by morteza2m** [comment]
Hi Dr. Jonny Huck, Excuse me.
my inputs for test viewshed, is:
 - radius: 100
 - centerX: 48.174
 - centerY: 33.374
 - observer height: 1.5
 - input File(is Dem file):
          [https://drive.google.com/file/d/0B7OpfZtVyXyudGpTcFdVcHdNcDQ/view?usp=sharing](url)
                   OR
          [https://drive.google.com/file/d/0B7OpfZtVyXyuVkR0blhOV000U28/view?usp=sharing](url)
 and set the proj4 to the following value:
         +proj=longlat +datum=WGS84 +no_defs
-------------------------

At first, are the values correct?
Then please guide me in running ./viewshed.
tanks.
