### ISSUE TITLE
how to run ./viewshed?

### ISSUE THREAD

**Issue by morteza2m** [jonnyhuck/Viewshed#7]
Hi Dr. Jonny Huck, Excuse me.
my input values for test viewshed, is:
 - radius: 100
 - centerX: 48.174
 - centerY: 33.374
 - observer height: 1.5
 - input File(is Dem file):
          https://drive.google.com/file/d/0B7OpfZtVyXyudGpTcFdVcHdNcDQ/view?usp=sharing
                   OR
          https://drive.google.com/file/d/0B7OpfZtVyXyuVkR0blhOV000U28/view?usp=sharing
 and set the proj4 to the following value:
         +proj=longlat +datum=WGS84 +no_defs
-------------------------

At first, are the values correct?
Then please guide me in running ./viewshed.
tanks.

**Comment by jonnyhuck** [comment]
Okay, there are a few things going on here:

1. you need to use a projected coordinate system (e.g. British National Grid, UTM and so forth)

2. you need to change the proj 4 string in the code as per my instructions last time. You will then need to compile the program as per the instructions in the README file

3. the command will be:

`./viewshed -r 100 -x [PROJECTED X COORD] -y [PROJECTED X COORD] -z [INPUT RESOLUTION] -o 1.5 -t [THE HEIGHT OF THE TARGET] -i DEM.tif -f VIEWSHED.tif`

Does that all make sense?

**Comment by am2222** [comment]
@jonnyhuck could you please help me about -z factor?Input resolution you mean pixel size on ground?in meters?

**Comment by jonnyhuck** [comment]
Exactly, it is the pixel size in the units of the projection that you are using (normally metres)
